import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavBar from './Components/NavBar/NavBar';
import Contact from './Components/Contact/Contact';
import { ProjectsProvider } from './context/ProjectsContext';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Hussein Kassab Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-indigo-950 to-violet-950 font-mono`}
      >
        <ProjectsProvider>
          <NavBar />
          {children}
          <Contact />
        </ProjectsProvider>
      </body>
    </html>
  );
}
